In [1]:
!pip install names
!pip install random
!pip install pandas

Collecting names
  Downloading names-0.3.0.tar.gz (789 kB)
     ---------------------------------------- 0.0/789.1 kB ? eta -:--:--
      --------------------------------------- 10.2/789.1 kB ? eta -:--:--
      --------------------------------------- 10.2/789.1 kB ? eta -:--:--
      --------------------------------------- 10.2/789.1 kB ? eta -:--:--
     - ----------------------------------- 30.7/789.1 kB 146.3 kB/s eta 0:00:06
     - ----------------------------------- 30.7/789.1 kB 146.3 kB/s eta 0:00:06
     -- ---------------------------------- 61.4/789.1 kB 204.8 kB/s eta 0:00:04
     ------ ----------------------------- 143.4/789.1 kB 448.2 kB/s eta 0:00:02
     -------------------------------------- 789.1/789.1 kB 2.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: names
  Building wheel for names (pyproject.toml): started
  Building wheel for names (pyproject.toml): finished with status 'done'
  Created wheel for names: filename=names-0.3.0-py3-none-any.whl size=803711 sha256=451aea66a862891f43ce7fc1c7c354103733a8d0e3348e1baf67c6674ec6fe85
  Stored in directory: c:\users\janjan wangbu\appdata\local\pip\cache\wheels\c7\f0\8f\de9f15941cd988c39b82703fa04cb2d550ba5867f13c6da052
Successfully built names
Installing collected packages: names
Successfully installed names-0.3.0

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement random (from versions: none)
ERROR: No matching distribution found for random

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\janjan wangbu\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\janjan wangbu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\janjan wangbu\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\janjan wangbu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\janjan wangbu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\janjan wangbu\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Importing libraries

In [3]:
import random
import pandas as pd
import names

Function for creating Team Table

In [4]:
def gen_team(n):
    team_names = set()
    while len(team_names) < n:
        team_names.add('Team ' + names.get_last_name())
    teams = pd.DataFrame({'Team_id': list(range(1, n + 1)),'Team_Name': list(team_names)})
    return teams

Function for creating Matches Table

In [6]:
def gen_match(team, number_of_matches):
    uniq_match = (len(team) - 1) * len(team) // 2

    #Raise Error due to the Input
    if number_of_matches < uniq_match:
      raise ValueError(f"Input Number of Matches ({number_of_matches}) is less than the possible Unique Matches ({uniq_match}).\n"
      + f"Input Greater than {uniq_match}")

    #Generate Unique Matches
    match_once = [(team.iloc[i, 0], team.iloc[l, 0]) for i in range(len(team)) for l in range(i + 1, len(team))]

    # Adding matches that may repeat
    add_match = []
    while len(add_match) < number_of_matches - uniq_match:
        x, y = random.sample(range(1,len(team)), 2)  # Generate two unique indices
        if x!=y:
          add_match.append((x, y))

    # Combine the unique and additional matches
    matches = match_once + list(add_match)

    # Randomized row of the matches and Tuple of W/L
    random.shuffle(matches)
    wl_shuffle = [(y, x) if random.choice([True, False]) else (x, y) for x, y in matches]

    # Prepare DataFrame
    matches_df = pd.DataFrame({
        'MATCH_NUMBER': range(1, number_of_matches + 1),
        'WINNER': [x for x, y in wl_shuffle],
        'LOSER': [y for x, y in wl_shuffle]
    })

    return matches_df

In [7]:
teams = gen_team(20)
teams

    Team_id        Team_Name
0         1       Team Moyer
1         2      Team Taylor
2         3   Team Collymore
3         4    Team Wickline
4         5        Team Mayo
5         6      Team Martin
6         7    Team Madewell
7         8     Team Padberg
8         9       Team Burns
9        10      Team Temple
10       11     Team Labarge
11       12        Team Wise
12       13       Team Almen
13       14       Team Sears
14       15     Team Pearson
15       16        Team Barr
16       17     Team Alberto
17       18     Team Mclarty
18       19    Team Campbell
19       20  Team Valdovinos

In [8]:
matches = gen_match(teams,200)
matches

     MATCH_NUMBER  WINNER  LOSER
0               1       5     15
1               2      20      5
2               3      10     16
3               4       1     15
4               5       8      5
..            ...     ...    ...
195           196       1     13
196           197      15     13
197           198      16     17
198           199       5      9
199           200      11     13

[200 rows x 3 columns]

Saving File to CSV

In [16]:
def df_to_csv(df, file_name):
    # df.to_csv(r"C:\Users\Janjan Wangbu\Downloads\Assignment4\ "+ file_name + ".csv", index=False)
    df.to_csv(r"C:\Users\Janjan Wangbu\Downloads\Assignment4\{0}.csv".format(file_name), index=False)

df_to_csv(teams,'Teams_Table')
df_to_csv(matches,'Matches_Table')

Assignment 4.2

SELECT t.Team_Name,t.Team_id, COUNT(m.WINNER) as Total_Wins
FROM Matches as m
JOIN Teams as t
ON t.Team_id == m.WINNER
GROUP BY t.Team_Name,t.Team_id
ORDER BY Total_Wins desc